### ISSUE TITLE
Explain common kubectl syntax (e.g: kubectl <action> <resources> <options>)

### ISSUE THREAD

**Issue by javaplus** [javaplus/DockerKubesDojo#3]
Explain common kubectl syntax for many commands... 
that is "kubectl <action> <resourcetype> <resourcename>"… (i.e. Actions this applies to: get, delete, scale, describe, edit, etc…)

This could be right with the Kubectl API understanding slides if it makes sense?

**Comment by frayer** [comment]
Closing this issue since I bundled the requirements under #2
